pipeline {
  agent any
  parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configurations')
      string(name: 'tag', defaultValue: 'all',  description: 'Tags to run ansible playbook against environments')
    }
  environment {
        current_space = 'dev'
        cpath = '/var/lib/jenkins/workspace/ansible-config-mgt_'+"${current_space}"+'/roles'
    }

 stages {
    stage('Clone Repo') {
      parallel {
        stage('Clone Repo') {
          steps {
            git branch: current_space, url: 'https://github.com/dipoesan/ansible-config-mgt.git'
          }
        }
    
        stage('Run playbook') {
          steps {
            ansiblePlaybook credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'Ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
          }
        }

        stage('Clean up') {
      steps {
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }
  }
}