pipeline {
  agent any
  environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
    }

  parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configurations')
    }
  
 stages {
        stage('Clone Repo') {
          steps {
            git branch: 'main', url: 'https://github.com/dipoesan/ansible-config-mgt.git'
          }
        }

        stage('Prepare Ansible For Execution') {
          steps {
            sh 'echo ${WORKSPACE}'
            sh 'sed -i \'s/roles_path = \\/var\\/lib\\/jenkins\\/workspace/roles_path = \\/var\\/lib\\/jenkins\\/workspace\\/ansible-project-14_main\\/roles /g\' deploy/ansible.cfg'
          }
        }
    
        stage('Run playbook') {
          steps {
            ansiblePlaybook credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'Ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
          }
        }

        stage('Clean up') {
          steps {
            cleanWs cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true
          }
        }
     
  }
}